# Generated by Django 3.2.15 on 2022-09-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects_table',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=500)),
                ('project_creator', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'projects_table',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='issues_table',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_title', models.CharField(max_length=100)),
                ('issue_description', models.CharField(max_length=100)),
                ('issue_repoter', models.CharField(max_length=100, null=True)),
                ('issue_type', models.CharField(choices=[('BUG', 'BUG'), ('TASK', 'TASK'), ('STORY', 'STORY'), ('EPIC', 'EPIC')], default='TASK', max_length=100)),
                ('issue_assignee', models.CharField(max_length=100)),
                ('issue_status', models.CharField(choices=[('Open', 'Open'), ('InProgress', 'InProgress'), ('InReview', 'In Review'), ('CodeComplete', 'Code Complete'), ('Done', 'Done')], default='Open', max_length=100)),
                ('project_title', models.ForeignKey(db_column='project_title', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='api.projects_table')),
            ],
            options={
                'db_table': 'issues_table',
            },
        ),
    ]
