# Generated by Django 3.2.15 on 2022-09-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='issues_table',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_title', models.CharField(max_length=100)),
                ('issue_description', models.CharField(max_length=100)),
                ('issue_repoter', models.CharField(max_length=100)),
                ('issue_type', models.CharField(choices=[('BUG', 'BUG'), ('TASK', 'TASK'), ('STORY', 'STORY'), ('EPIC', 'EPIC')], default='TASK', max_length=100)),
                ('issue_assignee', models.CharField(max_length=100)),
                ('issue_status', models.CharField(choices=[('Open', 'Open'), ('InProgress', 'InProgress'), ('InReview', 'In Review'), ('CodeComplete', 'Code Complete'), ('Done', 'Done')], default='Open', max_length=100)),
                ('project_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'issues_table',
            },
        ),
        migrations.CreateModel(
            name='projects_table',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=500)),
                ('project_creator', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'projects_table',
            },
        ),
        migrations.CreateModel(
            name='ticket_requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('Get_a_list_of_Projects_and_related_issues', 'Get a list of Projects and related issues'), ('Get_details_of_a_Project_by_title', 'Get details of a Project by title'), ('Create_a_Project', 'Create a Project'), ('Update_a_Project', 'Update a Project'), ('Delete_a_Project', 'Delete a Project'), ('Get_a_list_of_Issues', 'Get a list of Issues'), ('Get_details_of_an_Issue', 'Get details of an Issue'), ('Create_an_Issue', 'Create an Issue'), ('Update_an_Issue', 'Update an Issue'), ('Delete_an_Issue', 'Delete an Issue'), ('Get_a_list_of_Issues_under_a_Project', 'Get a list of Issues under a Project'), ('Get_details_of_an_Issue_under_a_Project', 'Get details of an Issue under a Project'), ('Create_an_Issue_under_a_Project', 'Create an Issue under a Project'), ('Update_an_Issue_under_a_Project', 'Update an Issue under a Project'), ('Delete_an_Issue_under_a_Project', 'Delete an Issue under a Project'), ('Assign_an_Issue_to_a_User', 'Assign an Issue to a User'), ('Update_the_Status_of_an_Issue', 'Update the Status of an Issue'), ('Search_Issue_on_title_and_description', 'Search Issue on title and description'), ('Get_a_list_of_users', 'Get a list of users')], max_length=300)),
                ('request_json', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ticket_requests',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
