# Generated by Django 3.2.15 on 2022-09-16 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues_table',
            name='assignlabel',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='issues_table',
            name='comments',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='issues_table',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='issues_table',
            name='time_allocated_in_day',
            field=models.IntegerField(default=None),
        ),
    ]
