# Generated by Django 3.2.15 on 2022-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_events_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_log',
            name='request_json',
            field=models.CharField(max_length=10000),
        ),
    ]
