# Generated by Django 3.2.15 on 2022-09-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_events_log_request_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues_table',
            name='watchers',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
